# Generated by Django 4.0 on 2022-05-10 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aereo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(default='', max_length=50, unique=True)),
                ('modello', models.CharField(default='', max_length=20)),
                ('miglie_max', models.IntegerField(default=0)),
                ('posti', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Aereo',
                'verbose_name_plural': 'Aerei',
            },
        ),
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('codice_iata', models.CharField(default='', max_length=50, unique=True)),
                ('lat_lng', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Aeroporto',
                'verbose_name_plural': 'Aeroporti',
            },
        ),
        migrations.CreateModel(
            name='Tratta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(default='', max_length=50, unique=True)),
                ('ora_partenza', models.TimeField()),
                ('ora_arrivo', models.TimeField()),
                ('data_partenza', models.DateField()),
                ('data_arrivo', models.DateField()),
                ('aereo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aeroporto.aereo')),
                ('aeroporto_arrivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aeroporto_arrivo', to='aeroporto.aeroporto')),
                ('aeroporto_partenza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aeroporto_partenza', to='aeroporto.aeroporto')),
            ],
            options={
                'verbose_name': 'Tratta',
                'verbose_name_plural': 'Tratte',
            },
        ),
    ]
